if: "(branch = master AND type = (pull_request OR cron)) OR (branch = dev)"
language: python
cache: pip
matrix:
  include:
    # Linux Installation.
    - os: linux
      python: 3.6
      sudo: true
      env:
        - MATRIX_EVAL="sudo apt-get install build-essential software-properties-common git unzip wget apt-utils uuid-dev -y"
        - LIBMEI_EVAL="cmake . && make"
    # Mac Installation.
    - os: osx
      # python: 3.6
      env:
        - HOMEBREW_NO_AUTO_UPDATE="1"
        - MATRIX_EVAL="brew install python3 ossp-uuid"
        - LIBMEI_EVAL="cmake -DCMAKE_FIND_FRAMEWORK=LAST && make"
before_install:
  # For testing without installing Rodan.
  - rm -rf __init__.py
  # Install OS dependencies.
  - eval "${MATRIX_EVAL}"
  # Install LibMEI.
  - git clone https://github.com/ddmal/libmei
  - cd libmei
  - eval "${LIBMEI_EVAL}"
  - cd ..
install:
  # Install python depedencies.
  - pip install -r requirements.txt
script:
- PYTHONPATH=. py.test
notifications:
  email: false
  slack:
    secure: FACw0TDYq19smgJ6IQNKWjMobWn4TgpKNE2W+XnxY9nwqB6d1ycGx5+8eRpdzUIJNHeB36+SG9rGVj5iTgvRuq6gwGexR8uVN5GKn0NZ10tlJQL9iD52d/CaqANCJ5y1H15AQzCuAMRgReLg3t/X2buaKkNVpV4YV0RBkXbulnaGi+8C/CPYf6uLhTQjqJkS63WB1PGRq3FUOFPzEAYsmvAJdu76E4goE99sQLWHonPN8HX645D0sFrUTKL+W8co35/4OPvTjdzLBFuKrV2Iti+3vPUHift9z8NZbbdgF7SmKCnl3MrCkCszG/zftUklfVeQ7d8rqm/zBXQ1FxWFo3EhbZcDwE9Uwd3m2tO9NnaONY7u8u1KmFSdzbAOixaq0jI06f9FME7uWC/oyPndtJWtHEuM6z+frdPxITkxoW9kAeklrwwn7H+VI66FVaDAsqLTUr1N0RBEUjhWdSe9Y4skJZCLAxh4QtHPSZPdAZZXjefAsiZadomMN2j2VX+4KAVHWz17aTSG14pWXF/KwRZxc0+dyHWyfPRPJzHTrr4UM2K2FWXC07xZF+FvUhCcj+gd4xuL2UXyVBHSQ/leq2JMspxiGzLG55NK9YfhLEotJURaii5/7YA+BXgpMRnniArEgrf8O076hShA0ZmsAtxWiLkcgwMnbCjYdMcmSa8=
